### ISSUE TITLE
May I ask you a question? Error: Process completed with exit code 128.

### ISSUE THREAD

**Issue by Final233** [timovv/notion-website-template#2] opened 2022-03-04 13:42 UTC
May I ask you a question?

I'm in github Action

Error Push to GitHub Pages

Run git config --global user.name "Final233"

git config --global user.name "Final233"

git config --global user.email "438803792@qq.com"

GIT_DEPLOY_DIR=dist/site \

GIT_DEPLOY_BRANCH=gh-pages \

GIT_DEPLOY_REPO="https://***@github.com/Final233/notion-website-loconotion.git" ./pages_repo/deploy.sh

shell: /usr/bin/bash -e {0}

fatal: not a git repository (or any of the parent directories): .git

Error: Process completed with exit code 128.

**Comment by reinaldoacdc** [comment] 2022-03-24 16:20
Me too.

**Comment by timovv** [comment] 2022-03-25 04:36
Hey folks, thanks for your patience. 

Looks like the deploy script was not having a good time for some reason -- I think the directories must have gotten mixed up. I could've sworn I had it working before, but I don't see why it would have broken... Regardless, I've pushed a fix. Please let me know if it resolves the issues you are seeing.

A separate issue, but worth noting: sometimes you have to run the build a second time to get things working (especially if you see an error about the `dist/site` directory not existing). I'm trying to find the root cause for this flakiness but haven't had any luck yet. If anybody would like to have a stab at it, be my guest!

**Closed as completed by timovv** 2022-03-25 04:36 UTC

**Comment by Final233** [comment] 2022-03-26 02:17
Thank you, the new version can be used, you need to add the Github token
